### ISSUE TITLE
/0 does not work as expected due to signed ints

### ISSUE THREAD

**Issue by killroy42** [rs/node-netmask#17]
0.0.0.0/0 does not match all IPs as expected. I guess there is a problem when calculating maskLong.
when mask = 0, it is expected that maskLong is 0x00000000 but it becomes 0xffffffff instead.

**Comment by jas-** [comment]
@rs  Thanks for the great module. Is this ever going to land?

**Comment by rs** [comment]
I need a pull request.

**Comment by jas-** [comment]
Whoops, never mind it was a reference.

**Comment by Ilya1st** [comment]
@rs +1 about a bug
> var block = new Netmask('0.0.0.0/0');
undefined
> block.size
4294967296 - right
> block.contains('1.1.1.1');
false

wrong.

**Comment by yuvadm** [comment]
👍 Is this getting fixed at any point?

**Comment by yuvadm** [comment]
@rs thanks for the fix! Any chance to get a 1.0.6 release?

**Comment by rs** [comment]
done
