### ISSUE TITLE
contains method returns wrong result

### ISSUE THREAD

**Issue by Bobozee** [rs/node-netmask#24]
`> netm = new Netmask('192.168.1.0/255.255.255.0')`
`Netmask {`
`  maskLong: 4294967040,`
`  bitmask: 24,`
`  netLong: 3232235776,`
`  size: 256,`
`  base: '192.168.1.0',`
`  mask: '255.255.255.0',`
`  hostmask: '0.0.0.255',`
`  first: '192.168.1.1',`
`  last: '192.168.1.254',`
`  broadcast: '192.168.1.255' }`
`> netm.contains('192.168.1.2')`
`false`
`>` 

expected result : true

**Comment by rs** [comment]
I can't reproduce:

`> var netmask = require('netmask');
undefined
> var n = new netmask.Netmask('192.168.1.0/255.255.255.0');
undefined
> n.contains('192.168.1.2');
true`

**Comment by Bobozee** [comment]
I do not know what went wrong. I cannot reproduce it as well. You can close this.

Thank you.
