### ISSUE TITLE
forEach only returns error 'fn not a function'

### ISSUE THREAD

**Issue by byoungdale** [rs/node-netmask#26]
When I'm trying to use the forEach method, I only get back 'fn is not a function'. No matter what input I use. 

What exactly am I supposed to input? The documentation shows ip, long, index. Not sure what long or index means, so I've been guessing. 

what kind of function am I supposed to input into the forEach method?

**Comment by rs** [comment]
You get the ip in dot notation, the IPv4 as long and the index of the IP in the iterated list. You might only need the first parameter.
