### ISSUE TITLE
Method first() returns incorrect IP address

### ISSUE THREAD

**Issue by AbrahamFriedman** [rs/node-netmask#29]
The first IP address of a block should end with .0 but first() returns an IP address of .1.

The Perl Net::Netmask, upon which this is based, says in the documentation: "->first() & ->last()    Synonyms for ->base() and ->broadcast()" and base should return the base address of the network block and broadcast should return the last IP address.

The code
@first = if @bitmask <= 30 then long2ip(@netLong + 1) else @base
should be moved after @base is set and changed to
@first = @base

In common usage, the first address in a subnet, all binary zero in the host identifier, is reserved for referring to the network itself, while the last address, all binary one in the host identifier, is used as a broadcast address for the network; this reduces the number of addresses available for hosts by 2.

While this is true, the actual CIDR range consists of the full set of IP addresses in the range even if those two IP address shouldn't be assigned to host machines.

**Comment by willydee** [comment]
I don't think this is to be considered an issue. The first sentence of the readme says "highly inspired by Perl Net::NetMask" but does NOT claim to be API compatible.

The API documentation is very clear that `first() and last()` are _not_ returning the base address or the broadcast address, but the first and last _useable_ address.
