### ISSUE TITLE
Accepts IPs with fewer than four octets, result doesn't make sense

### ISSUE THREAD

**Issue by cdhowie** [rs/node-netmask#45]
When constructing an instance with the form `x.y` I would expect one of two things:

1. An error because this is not a valid IP address.
2. The input to be parsed the same as `x.y.0.0/16`.

Instead, the input is parsed as `x.0.0.y/32`, which makes very little sense to me:

```
> (new netmask.Netmask('1.2')).toString()
'1.0.0.2/32'
```

The output is similarly odd when providing 1 or 3 octets:

```
> (new netmask.Netmask('1')).toString()
'0.0.0.1/32'
> (new netmask.Netmask('1.2.3')).toString()
'1.2.0.3/32'
```

**Comment by rs** [comment]
That how libc is doing it. Try ping 1.2.3 in a terminal.

**Comment by cdhowie** [comment]
Hmm, it might not be a bad idea to at least point out that the module implements parsing antiquated forms per `inet_aton()` which is a legacy function from 4.2BSD.  (POSIX's `inet_pton()` requires exactly 4 octets.)  I have a hard time imagining a situation in which this kind of parsing would be desirable unless one is _explicitly_ trying to match 4.2BSD's `inet_aton()` behavior.  It's entirely unexpected (IMO) on a runtime that does not directly expose libc bindings, and even then the choice of `inet_aton()` is odd to me given that `inet_pton()` exists and is actually part of POSIX.

Put another way, "matches 4.2BSD behavior" is not a goal I would expect from an npm module.  Not saying it's a bad idea, just that the module documentation doesn't indicate it.  I'm curious of the historical choice that led to this module's implementation following `inet_aton()`.  Is that something I can read up on?

**Comment by rs** [comment]
Node is using the libc.

Try it by yourself:

```
const net = require('net');
(new net.Socket()).connect(80, '1.1', function() {
	console.log('Connected to ' + this.remoteAddress);
});

> Connected to 1.0.0.1
```
